#!/bin/sh /etc/rc.common

# Copyright 2022 InvizBox Ltd
#
# Licensed under the InvizBox Shared License;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        https://www.invizbox.com/lic/license.txt

START=94
boot() {
	rm -f /etc/config/.*.uci-*
}
