#!/bin/ash

# Copyright 2018 InvizBox Ltd
#
# Licensed under the InvizBox Shared License;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        https://www.invizbox.com/lic/license.txt
#
# This is here to set the urls and version correctly after a sysupgrade with kept settings

uci -c /rom/etc/config show update | grep "\.urls\." | xargs -n 1 uci set
uci -c /rom/etc/config show update | grep "\.server\." | xargs -n 1 uci set
uci set update.version.firmware=%V
uci set update.version.new_firmware=
uci commit update

mkdir -p /etc/opkg_clear
sed "s|http://invizboxinobxs4f.onion|https://update.invizbox.com|g" /etc/opkg/distfeeds.conf > /etc/opkg_clear/distfeeds.conf
