#!/bin/ash

# Copyright 2016 InvizBox Ltd
#
# Licensed under the InvizBox Shared License;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        https://www.invizbox.com/lic/license.txt
. /bin/mtdutils.sh

wifi_password=$(dd if=/dev/mtd2 bs=1 skip=65520 count=16)

if [ $(uci get wireless.lan.key) == "TOKENPASSWORD" ]; then
    passwd root <<EOF
${wifi_password}
${wifi_password}
EOF
    validate_string_ascii ${wifi_password}
    if [ $? -eq 0 ]; then
        sed -i "s/TOKENPASSWORD/${wifi_password}/g" /etc/config/wireless
    fi
fi

vpn_username=`dd if=/dev/mtd2 bs=1 skip=65432 count=64 | tr -d ' '`

if [ -z $(uci get vpn.active.username) ]; then
    validate_string_ascii ${vpn_username}
    if [ $? -eq 0 ]; then
        uci set vpn.active.username=${vpn_username}
        uci commit vpn
    fi
fi

vpn_password=`dd if=/dev/mtd2 bs=1 skip=65496 count=24 | tr -d ' '`

if [ -z $(uci get vpn.active.password) ]; then
    validate_string_ascii ${vpn_password}
    if [ $? -eq 0 ]; then
        uci set vpn.active.password=${vpn_password}
        uci commit vpn
    fi
fi

if [ ! -s /etc/openvpn/login.auth ]; then
    validate_string_ascii ${vpn_username}
    if [ $? -eq 0 ]; then
        validate_string_ascii ${vpn_password}
        if [ $? -eq 0 ]; then
            echo -e ${vpn_username}"\n"${vpn_password} > /etc/openvpn/login.auth
        fi
    fi
fi
