#!/bin/ash

# Copyright 2018 InvizBox Ltd
#
# Licensed under the InvizBox Shared License;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        https://www.invizbox.com/lic/license.txt
. /bin/mtdutils.sh

wifi_password=$(cat /private/wifi_password.txt)

if [ $(uci get wireless.lan.key) == "TOKENPASSWORD" ]; then
    validate_string_ascii ${wifi_password}
    if [ $? -eq 0 ]; then
        passwd root <<EOF
${wifi_password}
${wifi_password}
EOF
        sed -i "s/TOKENPASSWORD/${wifi_password}/g" /etc/config/wireless
        sed -i "s/TOKENPASSWORD/${wifi_password}/g" /etc/config/rest-api
    fi
fi

read vpn_username vpn_password <  /private/vpn_credentials.txt
if [ ! -s /etc/openvpn/login.auth ]; then
    echo -e ${vpn_username}"\n"${vpn_password} > /etc/openvpn/login.auth
fi
if [ -z $(uci get vpn.active.username) ]; then
    validate_string_ascii ${vpn_username}
    if [ $? -eq 0 ]; then
        uci set vpn.active.username=${vpn_username}
        uci commit vpn
    fi
fi

if [ -z $(uci get ipsec.vpn_1.eap_identity) ]; then
    if [ $(uci get admin-interface.features.separate_ipsec_credentials) == "true" ]; then
        read ipsec_username ipsec_password <  /private/ipsec_credentials.txt
    else
        read ipsec_username ipsec_password <  /private/vpn_credentials.txt
    fi
    validate_string_ascii ${ipsec_username}
    if [ $? -eq 0 ]; then
        uci set ipsec.vpn_1.eap_identity=${ipsec_username}
        uci set ipsec.vpn_2.eap_identity=${ipsec_username}
        uci set ipsec.vpn_3.eap_identity=${ipsec_username}
        uci set ipsec.vpn_4.eap_identity=${ipsec_username}
        uci commit ipsec
    fi
    validate_string_ascii ${ipsec_password}
    if [ $? -eq 0 ]; then
        uci set ipsec.vpn_1.eap_password=${ipsec_password}
        uci set ipsec.vpn_2.eap_password=${ipsec_password}
        uci set ipsec.vpn_3.eap_password=${ipsec_password}
        uci set ipsec.vpn_4.eap_password=${ipsec_password}
        uci commit ipsec
    fi
fi
