#!/bin/sh /etc/rc.common
# Copyright 2016 InvizBox Ltd
# https://www.invizbox.com/lic/license.txt

START=40
APP=rest_api.py
USE_PROCD=1

start_service() {
	procd_open_instance rest-api
	procd_set_param command /usr/lib/python3.6/site-packages/rest_api/${APP}
	procd_set_param env JWT_SECRET=$(cat /etc/jwt_secret)
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_append_param respawn 3600
	procd_append_param respawn 5
	procd_append_param respawn 0
	procd_close_instance
}

reload_service() {
	procd_send_signal rest-api rest-api USR1
}

service_triggers() {
	procd_add_reload_trigger "vpn"
}
