#!/bin/ash

# Copyright 2016 InvizBox Ltd
#
# Licensed under the InvizBox Shared License;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        https://www.invizbox.com/lic/license.txt

wifi_password=$(dd if=/dev/mtd2 bs=1 skip=65520 count=16)

if [ $(uci get wireless.ap.key) == "TOKENPASSWORD" ]; then
    /usr/bin/passwd root <<EOF
${wifi_password}
${wifi_password}
EOF
    uci set wireless.ap.key=${wifi_password}
    uci commit wireless
fi

vpn_username=$(dd if=/dev/mtd2 bs=1 skip=65432 count=64)

if [ -z $(uci get vpn.active.username) ]; then
    uci set vpn.active.username=${vpn_username}
    uci commit vpn
fi

vpn_password=$(dd if=/dev/mtd2 bs=1 skip=65496 count=24)

if [ -z $(uci get vpn.active.password) ]; then
    uci set vpn.active.password=${vpn_password}
    uci commit vpn
fi