#!/bin/ash

# Copyright 2018 InvizBox Ltd
#
# Licensed under the InvizBox Shared License;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        https://www.invizbox.com/lic/license.txt

. /bin/ledcontrol.ash
led_info_off

if [ ! -s /etc/lighttpd/inviz.box.pem ]; then
    openssl req \
    -x509 \
    -config /etc/openssl-inviz.box.config \
    -newkey rsa:4096 \
    -nodes \
    -days 5844 \
    -keyout /tmp/inviz.box.key \
    -out /tmp/inviz.box.crt

    # create pem file
    cat /tmp/inviz.box.key /tmp/inviz.box.crt > /etc/lighttpd/inviz.box.pem
fi

if [ ! -s /etc/jwt_secret ]; then
    dd if=/dev/urandom skip=0 count=32 bs=1 | hexdump -e '"%x"' > /etc/jwt_secret
fi
