#!/bin/ash

# Copyright 2018 InvizBox Ltd
#
# Licensed under the InvizBox Shared License;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        https://www.invizbox.com/lic/license.txt

. /lib/functions.sh
. /bin/invizboxutils.sh

uci set rest-api.version=version
uci set rest-api.version.api=%V
uci commit rest-api

if [ ! -s /etc/jwt_secret ]; then
    dd if=/dev/urandom skip=0 count=32 bs=1 | hexdump -e '"%x"' > /etc/jwt_secret
fi

pre_update_version=$(uci get update.version.firmware)
provider_id=$(uci get vpn.active.provider)

if [ "$(version "${pre_update_version}")" -lt "$(version 0.0.41)" ]; then
    # add protocol IDs if needed (from IPSec onwards)
    protocol_id=openvpn_tcp_443
    ip_protocol=TCP
    port=443
    if [ "${provider_id}" == "expressvpn" ]; then
        protocol_id=openvpn_udp_1195
        ip_protocol=UDP
        port=1195
    elif [ "${provider_id}" == "pia" ]; then
        protocol_id=openvpn_tcp_501
        ip_protocol=TCP
        port=501
    elif [ "${provider_id}" == "vanishedvpn" ]; then
        protocol_id=openvpn_udp_1194
        ip_protocol=UDP
        port=1194
    fi

    first_protocol_id=$(grep -m1 "config protocol" /etc/config/vpn | awk '{print $3}' | cut -d "'" -f 2)
    if [ "$first_protocol_id" == "" ]; then
        uci set vpn.$protocol_id=protocol
        uci set vpn.$protocol_id.vpn_protocol=OpenVPN
        uci set vpn.$protocol_id.ip_protocol=$ip_protocol
        uci set vpn.$protocol_id.port=$port
        if [ "${provider_id}" == "windscribe" ]; then
            uci set vpn.ikev2_ipsec=protocol
            uci set vpn.ikev2_ipsec.vpn_protocol=IKEv2
            uci set vpn.ikev2_ipsec.ip_protocol=IPSec
            uci set vpn.ikev2_ipsec.port=50
        fi
    fi
    uci commit vpn
    first_server=$(grep -m1 "config server" /etc/config/vpn | awk '{print $3}' | cut -d "'" -f 2)
    if [ -z "$(uci get "vpn.$first_server.protocol_id")" ]; then
        if [ "${provider_id}" == "windscribe" ]; then
            sed -i "s/\toption template/\tlist protocol_id '${protocol_id}'\n\tlist protocol_id 'ikev2_ipsec'\n\toption template/g" /etc/config/vpn
        else
            sed -i "s/\toption template/\tlist protocol_id '${protocol_id}'\n\toption template/g" /etc/config/vpn
        fi
    fi
fi

if [ "$(version "${pre_update_version}")" -lt "$(version 0.1.0)" ]; then
    rewrite_protocol()
    {
        vpn_protocol=$(uci get "vpn.$1.vpn_protocol")
        ip_protocol=$(uci get "vpn.$1.ip_protocol")
        port=$(uci get "vpn.$1.port")
        uci set "vpn.$1.name=$vpn_protocol over $ip_protocol port $port"
        uci set "vpn.$1.template=$first_template"
        for server in $(uci get dhcp.vpn1.server)
        do
            case "$server" in
                *@tun1) uci add_list "vpn.$1.dns_server=${server::-5}" ;;
            esac
        done
        uci del "vpn.$1.ip_protocol"
        uci del "vpn.$1.port"
    }

    first_template=$(grep -m1 "option template" /etc/config/vpn | awk '{print $3}' | cut -d "'" -f 2)
    sed -i "/option template/d" /etc/config/vpn
    protocols=$(grep "config protocol" /etc/config/vpn | awk '{print $3}' | cut -d "'" -f 2)
    for protocol in $protocols
    do
        rewrite_protocol "$protocol"
    done
    uci commit vpn
fi
