#!/bin/sh /etc/rc.common
# Copyright 2019 InvizBox Ltd
# https://www.invizbox.com/lic/license.txt

START=99
APP=irqbalance
USE_PROCD=1

start_service() {
	procd_open_instance irqbalance
	procd_set_param command /usr/sbin/${APP} --foreground
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_append_param respawn 3600
	procd_append_param respawn 5
	procd_append_param respawn 0
	procd_close_instance
}
